### ISSUE TITLE
Convert tests away from expectations to clojure.test

### ISSUE THREAD

**Issue by ricardojmendez** [Taoensso/faraday#101]
Migrate tests.  Discussed on issue #100

**Comment by ricardojmendez** [comment]
Looks like `expectations` [is in for some changes](https://groups.google.com/forum/#!topic/clojure/z9b5Ws9EVXQ), in case this changes your view of it @ptaoussanis.

**Comment by ptaoussanis** [comment]
Hi Ricardo,

Thanks for pinging me about this. The announcement doesn't affect my general preference to change, would be happy to explain why by email if you're interested (feel free to ping).

In any case, migrating tests would be a _really_ low priority so something that there might never well concretely be sufficient motivation for anyone to actually do :-)

**Comment by ricardojmendez** [comment]
Sure, would love to hear about it  - please shoot me an e-mail.
