### ISSUE TITLE
Remove support for `:expected`

### ISSUE THREAD

**Issue by ricardojmendez** [Taoensso/faraday#105]
It looks like it's not long for this world, as some of my tutorial examples were already failing. Replace on tests with `:cond-expr` and, where necessary, `:expr-attr-names`.

**Comment by belucid** [comment]
Taking this one on for 1.10.

**Comment by kipz** [comment]
Is this still something we want for 1.10 @belucid ?

**Comment by joelittlejohn** [comment]
After some further discussion on this one, we decided that without a strong reason to take this out, we should probably leave it in. It's sign-posted as deprecated but there's no reason to break upgrades for anyone that's using it. It looks like it will remain deprecated but usable in the AWS SDK.

If we do a major Faraday overhaul with some major breaking changes, we can reconsider.
