### ISSUE TITLE
Request: custom keywordization routine

### ISSUE THREAD

**Issue by acron0** [Taoensso/faraday#111]
It'd be nice if keywordization of results was optional, or that a custom function could be provided rather than `keyword`:

https://github.com/ptaoussanis/faraday/blob/master/src/taoensso/faraday.clj#L357

**Comment by kipz** [comment]
@acron0 this doesn't seem unreasonable to me. What do others think?

**Comment by acron0** [comment]
The link doesn't point to the correct line any more, but I think people get the gist still !

**Comment by joelittlejohn** [comment]
This is a nice idea, but I'm going to close it as I don't think it's necessary.

Many Clojure libraries do without this level of customization, and it's always possible to stringify (or whatever) later. This is the kind of configurability that introduces more complexity over time and gives us more possible branches to support.
