### ISSUE TITLE
Add support for DynamoDB Transactions

### ISSUE THREAD

**Issue by swvist** [Taoensso/faraday#122]
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transactions.html

**Comment by belucid** [comment]
Yup, this is important. Hoping to include it in the next release @swvist.

**Comment by belucid** [comment]
https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-transactions/

**Comment by swvist** [comment]
Hi @belucid, there is an initial PR at #123

**Comment by belucid** [comment]
Perfect... I'll take a look at it tomorrow and provide some initial feedback.

**Comment by swvist** [comment]
@belucid, #123 now supports all Dynamo DB transaction APIs and is ready for initial feedback. I am yet to add inline documentation for the new API but otherwise the PR is complete.

**Comment by kipz** [comment]
@swvist are you able to rebase your fork and get #123 moving again? We're all very keen to get this support in ASAP.
