### ISSUE TITLE
Upload all doc versions to http://taoensso.github.io/faraday/{version}

### ISSUE THREAD

**Issue by joelittlejohn** [Taoensso/faraday#138]
Each time we create a new release, we should include new docs at http://taoensso.github.io/faraday/ with the version in the path (so that all old doc versions are still present).

We can generate the docs for all historical versions as part of this update.

**Comment by belucid** [comment]
Hey @joelittlejohn 

Thanks for all the good work on the PRs recently. That's awesome.

Speaking of versioning though. I noticed you pulled together the recent changes into a `1.9.0-beta1` version (BTW referred to in 1 spot in the change notes as `1.9.0-RC1`) which is great to make these available and get some people trying it. I went to switch over to it to try it out.

Not sure `1.9.x` is ideal though as there have already been release in the `1.10.x` family: https://clojars.org/com.taoensso/faraday/versions

Seems we should go to `1.11.x` for the new work, y?

**Comment by joelittlejohn** [comment]
Hi @belucid. I'm not sure what you mean by this. Where did you see 1.9.0-beta1 being created?

The releases I've created so far are:
* v1.10.0-alpha2
* v1.10.0-alpha3
* v1.10.0 (GA)

**Comment by joelittlejohn** [comment]
Our next release will (probably, depending on the changes) be 1.11.0.

**Comment by joelittlejohn** [comment]
Looks like 1.9.0-beta1 was created by Peter T in January 2016:

https://github.com/Taoensso/faraday/commit/4cb1510436712173991eee181a0f4651e9457109

**Comment by belucid** [comment]
Ah... ok... that's good. Well... if you go to releases in GitHub, it's a bit funky. Makes it look like that was done by you 7 days ago.

**Comment by belucid** [comment]
Maybe we need to do a GH release of `1.10.0` to address that.

**Comment by belucid** [comment]
Hmm... and never mind that too. I refreshed the page and now it's got Peter by that release and not you. Ughh... looks like it was just a GH glitch. Sorry for the false alarm @joelittlejohn . I'll delete these messages to clean up this issue thread.
