### ISSUE TITLE
missing page-size/max-result-size option with query

### ISSUE THREAD

**Issue by brenourban** [Taoensso/faraday#148]
Folks, I did not find the page-size option to control the number of items on one page. I'd like to do a paginated query, but as far as I understand, limit is not the best option to do a pagination. 

I was following this doc : https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.Pagination.html

**Comment by joelittlejohn** [comment]
That doc describes using the option `--page-size`, and the `--page-size` option is translated to `Limit` in the DynamoDB request by the AWS CLI. If you want to see this happening you can invoke the CLI with the `--debug` flag.

To do pagination you want to use the `:limit` option and then request subsequent pages using `:limit` and `:last-prim-kvs`.
