### ISSUE TITLE
not listing tables

### ISSUE THREAD

**Issue by sibelius** [Taoensso/faraday#151]
I can query dynamodb tables using this command line

```jsx
aws dynamodb list-tables --endpoint-url http://localhost:8000
```

that returns 2 tables for me

however doing this using `lein repl`

```clojure
(require '[taoensso.faraday :as far])
(def client-opts { :access-key 'access-key' :secret-key 'secret-key' :endpoint 'http://localhost:8000'})
(far/list-tables client-opts)
```

does not return any tables

what am I doing wrong?

I've tried many approaches:

using docker:

`docker run -p 8000:8000 amazon/dynamodb-local`

using lein `lein dynamodb-local`

I can see tables using `https://github.com/aaronshaf/dynamodb-admin`

**Comment by sibelius** [comment]
version: `[com.taoensso/faraday "1.11.0-alpha1"]`

**Comment by ianffcs** [comment]
maybe you have a .aws config that is shadowing your current ":endpoint" keyword value, maybe pass :endpoint "http://localhost:6798" to client-opts map?

**Comment by sibelius** [comment]
I have this

`(def client-opts { :access-key 'access-key' :secret-key 'secret-key' :endpoint 'http://localhost:8000'})`

is this enough?

how can I debug this further?

**Comment by kipz** [comment]
Shouldn't the values be double quotes to make map values into strings? Perhaps a copy/paste issue?

```clojure
(def client-opts { :access-key "" :secret-key "" :endpoint ""})
```
Though I expect you would see some exceptions if they weren't strings

**Comment by sibelius** [comment]
I've tried this

`(def client-opts { :access-key "" :secret-key "" :endpoint "http://localhost:8000"})`

and it is not working as well

**Comment by sibelius** [comment]
this is how I'm creating my tables

table definition: based on https://github.com/runopsio/sequence
```jsx
{
  "TableName": "decimals",
  "ProvisionedThroughput": { "ReadCapacityUnits": 1, "WriteCapacityUnits": 1 },
  "AttributeDefinitions": [
    { "AttributeName": "PK", "AttributeType": "S" },
    { "AttributeName": "SK", "AttributeType": "S" },
    { "AttributeName": "GSI1_PK", "AttributeType": "S" },
    { "AttributeName": "LSI1_SK", "AttributeType": "S" },
    { "AttributeName": "GSI1_SK", "AttributeType": "S" }
  ],
  "KeySchema": [
    { "AttributeName": "PK", "KeyType": "HASH" },
    { "AttributeName": "SK", "KeyType": "RANGE" }
  ],
  "GlobalSecondaryIndexes": [
    {
      "IndexName": "LSI1",
      "KeySchema": [
        { "AttributeName": "PK", "KeyType": "HASH" },
        { "AttributeName": "LSI1_SK", "KeyType": "RANGE" }
      ],
      "Projection": { "ProjectionType": "ALL" },
      "ProvisionedThroughput": {
        "ReadCapacityUnits": 1,
        "WriteCapacityUnits": 1
      }
    },
    {
      "IndexName": "GSI1",
      "KeySchema": [
        { "AttributeName": "GSI1_PK", "KeyType": "HASH" },
        { "AttributeName": "GSI1_SK", "KeyType": "RANGE" }
      ],
      "Projection": { "ProjectionType": "ALL" },
      "ProvisionedThroughput": {
        "ReadCapacityUnits": 1,
        "WriteCapacityUnits": 1
      }
    }
  ]
}
```

create table using dynamodb cli
```jsx
aws dynamodb create-table --cli-input-json file://sequence.json --endpoint-url http://localhost:8000
```

list tables
```jsx
aws dynamodb list-tables --endpoint-url http://localhost:8000
```

**Comment by kipz** [comment]
Do these steps work for you as they do for me?

```shell
docker run -p 8000:8000 amazon/dynamodb-local
```

```clojure
(require '[taoensso.faraday :as far])
(def client-opts {:access-key "" :secret-key "" :endpoint "http://localhost:8000"})
(far/list-tables client-opts)
;; => ()
;; from the docs
(far/create-table client-opts :my-table
                             [:id :n]  ; Primary key named "id", (:n => number type)
                             {:throughput {:read 1 :write 1} ; Read & write capacity (units/sec)
                              :block? true ; Block thread during table creation
                              })
(far/list-tables client-ops)
;; =>  (:my-table)
```

Almost certainly not related, but are you able to upgrade to the latest release from the alpha?

**Comment by sibelius** [comment]
I've made a javascript script to list tables similar to far/list-tables

https://gist.github.com/sibelius/6430d1ad9390b83a40f1c600d7c159f1

If I do (far/create-table) I can see the table in (far/list-tables) 

the problem is to list already existing tables

one problem that I see with (far/create-table) is that I can't see that table using

aws dynamodb cli, neither using dynamodb admin (https://github.com/aaronshaf/dynamodb-admin)

it looks like it is querying a different database

can I specify the region of my database?

**Comment by kipz** [comment]
I agree. Seems like somehow you are connecting to a different database.

You can pass in `:region` in the client-opts map instead of the `:endpoint` (as of version 1.11.0 I think)

**Comment by sibelius** [comment]
`(def client-opts { :access-key "dummy" :secret-key "dummy" :endpoint "http://localhost:8000" :region "us-east-1"})`

this get me this error on region

```jsx
Cannot cast java.lang.String to com.amazonaws.regions.Region
```

**Comment by kipz** [comment]
I'm not sure it makes sense to set a region as well as an endpoint, but in any case, I think you've stumbled on a bug. I've raised it [here](https://github.com/Taoensso/faraday/issues/152).

However, I think bug is unrelated to what you are seeing with the different databases - you should be able to continue using `endpoint` in client-opts.

**Comment by sibelius** [comment]
not sure what the problem was, maybe some old dynamodb running

I've changed the dynamolocal, and it is working fine now

tks

**Comment by kipz** [comment]
Glad it's all working now.

**Comment by sibelius** [comment]
this stackoverflow can give more insights for the issue

https://stackoverflow.com/questions/29558948/dynamo-local-from-node-aws-all-operations-fail-cannot-do-operations-on-a-non-e

it looks like if you are using different profiles you get different databases 

can I set a profile in `client-opts` ?
