### ISSUE TITLE
String index names cause type error

### ISSUE THREAD

**Issue by JonathanHarford** [Taoensso/faraday#159]
It seems that the intent of #121 was to allow both keywords and strings as table/index names, but it seems like there was a regression in subsequent change (quite likely ee2e65d8634cb97f9a339454d3e2481e72971c95) that made it so string index/table names cause a type error: `java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IFn`

Was this an intentional change? We're happy to work on a patch if not.

You can reproduce this by changing `bulk-table` in `tests/main.clj` to a string.

**Comment by kipz** [comment]
Thanks for the bug report @JonathanHarford, and for all the digging.

It does look like a regression has sneaked in here.

A PR with the modified test passing would be most welcome!

**Comment by JonathanHarford** [comment]
Great, I'll tackle it later this week.

**Comment by joelittlejohn** [comment]
Closed by #160.
