### ISSUE TITLE
Possibly confusing dependencies found

### ISSUE THREAD

**Issue by bitti** [Taoensso/faraday#163]
Currently the build for a project which contains the `[com.taoensso/faraday "1.11.4"]` dependency with `:pedantic true` is failing due to:

```
Possibly confusing dependencies found:
[com.taoensso/faraday "1.11.4"] -> [com.taoensso/encore "2.127.0"] -> [org.clojure/tools.reader "1.3.2"]
 overrides
[com.taoensso/faraday "1.11.4"] -> [com.taoensso/nippy "2.15.3"] -> [org.clojure/tools.reader "1.3.3"]

Consider using these exclusions:
[com.taoensso/faraday "1.11.4" :exclusions [org.clojure/tools.reader]]
```

Since `com.taoensso/encore` has the same project owner it shouldn't be a problem to get the versions of `org.clojure/tools.reader` aligned?

**Comment by kipz** [comment]
Thanks @bitti - shall we try to get the version upgraded in encore since it's older?

**Comment by kipz** [comment]
Or we can update encore...not sure how much effort that is...

**Comment by bitti** [comment]
Sure if you can update it that may be the best solution but thanks for the quick exclusion fix!

**Comment by kipz** [comment]
@bitti upgrading the major version looks like it could have a few issues, so perhaps this could do for now? Or perhaps you'd be up for a PR? I think this came up before..... @joelittlejohn?
