### ISSUE TITLE
FYI: have pushed some superficial changes

### ISSUE THREAD

**Issue by ptaoussanis** [Taoensso/faraday#165]
@joelittlejohn Hi Joe - I hope you're well!

Just a heads-up that I took the liberty of pushing a few small [commits](https://github.com/Taoensso/faraday/commits/master) to Faraday master.

These are all superficial / admin-related, so I didn't bother with a PR - I hope that's okay?

The changes should all be self-explanatory (or should have a commit description). High-level motivation is to help keep all the Taoensso libs approximately in sync on things like tested platforms, etc.

Feel free to close, or ping if you have any objections.

Cheers :-)

**Comment by joelittlejohn** [comment]
Great stuff, sounds good!

We haven't had changes here in a while, but funnily enough, in the last few days we've been making changes to support more of the recent config options for tables. So good timing!
