### ISSUE TITLE
Add convenient support for new DynamoDB lib features

### ISSUE THREAD

**Issue by ptaoussanis** [Taoensso/faraday#6]
**Transaction library** (July 2013): http://aws.typepad.com/aws/2013/07/dynamodb-transaction-library.html
**Local testing library** (Sep 2013): http://aws.typepad.com/aws/2013/09/dynamodb-local-for-desktop-development.html
**Geospatial library** (Sep 2013): http://aws.typepad.com/aws/2013/09/new-geo-library-for-dynamodb-.html

Anything else?

Will be swamped with work for the next few months, so any assistance with these would be very welcome. All libs expose a simple(ish) Java API; would just need a little wrapping to make them more convenient to use from Clojure/Faraday.

**Comment by joelittlejohn** [comment]
Closing this one as I think we have the main parts covered elsewhere. If anyone is interested in integrating the geo library in some way, please open a new issue or PR.
